[mesos]
# master = "zk://localhost/mesos"
# listen = "0.0.0.0"

[zookeeper]
# endpoint = "zk://localhost/openvdc"

[api]
# endpoint = "localhost:5000"

[scheduler]
# id = "scheduler_1"
# name = "openvdc"
# failover-timeout = 604800 #1 week
# executor-path = "openvdc-executor"
# auto-reconnect = true
